version: "2"
services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
    ports:
      - 3306:3306
  api:
    build:
      context: ./docker/platform
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    links:
      - web
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: ushahidi
      MYSQL_USER: ushahidi
      MYSQL_PASSWORD: ushahidi
      WEB_HOST: web
      WEB_PORT: '8080'
    volumes:
      - ${PLATFORM_DIR}:/vols/src:ro
    ports:
      - ${PORT}:80
    volumes_from:
      - web
  web:
    build:
      context: ./docker/platform-client
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ${PLATFORM_CLIENT_DIR}:/vols/src:ro
    environment:
      BACKEND_URL: "./"
      GITHUB_TOKEN: ${GITHUB_TOKEN}
